name: ðŸš€ Entrega Continua Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Cambiado a Linux porque Azure SWA runner funciona mejor con Linux

    steps:
      - name: ðŸ“¥ Clonar repositorio
        uses: actions/checkout@v4

      - name: ðŸ§° Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ðŸ“¦ Instalar dependencias
        run: npm install

      - name: ðŸ”¨ Build Angular
        run: npm run build --prod

      - name: ðŸš€ Desplegar a Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                       # raÃ­z del proyecto
          output_location: "dist/restobar-kronos"  # carpeta generada por ng build
